networks:
  gleam-cake-test:
    name: gleam-cake-test

services:
  postgres:
    container_name: gleam-cake-test-postgres
    networks:
      - gleam-cake-test
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gleam_cake_test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker/data/postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  mariadb:
    container_name: gleam-cake-test-mariadb
    networks:
      - gleam-cake-test
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_DATABASE: "gleam_cake_test"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
