networks:
  gleam-cake-test:
    name: gleam-cake-test

services:
  postgres:
    container_name: gleam-cake-test-postgres
    networks:
      - gleam-cake-test
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gleam_cake_test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker/data/postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  # mariadb:
  #   container_name: gleam-cake-test-mariadb
  #   networks:
  #     - gleam-cake-test
  #   image: mariadb:latest
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:3306:3306"
  #   environment:
  #     MARIADB_DATABASE: "gleam_cake_test"
  #     MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
  #     MYSQL_ROOT_HOST: "%"
  #     MARIADB_ROOT_HOST: "%"
  #   dns:
  #     - 1.1.1.1
  #     - 127.0.0.11
  #   command: "mysqld --log-bin-trust-function-creators=1 --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_bin"

  mariadb:
    container_name: gleam-cake-test-mariadb
    dns:
      - 1.1.1.1
      - 127.0.0.11
    image: "mariadb:latest"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./docker/data/maria-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: "gleam_cake_test"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      # MYSQL_DATABASE: "gleam_cake_test"
      # MYSQL_ALLOW_EMPTY_PASSWORD: true

volumes:
  gleam-cake-test:
