name = "cake_demo_select_and_decode"
description = "A demo of using Gleam with Cake and 🐘PostgreSQL to run SELECT queries and decode returning data into Gleam records"
gleam = ">= 1.15.0"

[dependencies]
cake = { path = "../../" }
cake_pog = ">= 1.5.0 and < 2.0.0"
gleam_stdlib = ">= 0.71.0 and < 2.0.0"
examples_helper = { path = "../examples_helper" }
