name = "cake_demo_union_and_decode"
description = "An demo of using Gleam with Cake and Postgres to run UNION queries and decode returning data into Gleam records"

[dependencies]
cake = ">= 0.8.0 and < 2.0.0"
gleam_pgo = ">= 0.12.0 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
demo_helper = { path = "../demo_helper" }
