name = "cake_demo_insert"
description = "An demo of using Gleam with Cake and Postgres to run INSERT queries"

[dependencies]
cake = { path = "../../../" }
demo_helper = { path = "../demo_helper" }
gleam_pgo = ">= 0.12.0 and < 2.0.0"
gleam_stdlib = ">= 0.39.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
