name = "examples_helper"
description = "An examples helper for Cake"
gleam = ">= 1.15.0"

[dependencies]
cake = { path = "../../" }
cake_pog = ">= 1.2.0 and < 2.0.0"
gleam_stdlib = ">= 0.62.0 and < 2.0.0"
