name: Test

on:
  workflow_call:
    inputs:
      gleam_version:
        type: string
        required: true
        default: "1"
      test_erlang:
        type: boolean
        default: true
      erlang_version:
        type: string
        default: "27"
      test_node:
        type: boolean
        default: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/install_gleam@main
        with:
          gleam_version: ${{inputs.gleam_version}}
          erlang_version: ${{inputs.erlang_version}}
      - uses: TanklesXL/gleam_actions/.github/actions/format@main

  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/install_gleam@main
        with:
          gleam_version: ${{ inputs.gleam_version }}
          erlang_version: ${{ inputs.erlang_version }}
      - uses: TanklesXL/gleam_actions/.github/actions/deps_cache@main
        with:
          gleam_version: ${{ inputs.gleam_version }}

  test_erlang:
    if: inputs.test_erlang
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      # mariadb:
      #   image: mariadb:latest
      #   ports:
      #     - 3306:3306
      #   env:
      #     MARIADB_DATABASE: gleam_cake_test
      #     MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      #   options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql:
        image: mysql:latest
        ports:
          - 3308:3308
        env:
          MYSQL_DATABASE: "gleam_cake_test"
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_TCP_PORT: 3308
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    needs: deps
    strategy:
      fail-fast: true
      matrix:
        erlang: ["27"]
    steps:
      - uses: actions/checkout@v4
      - uses: TanklesXL/gleam_actions/.github/actions/deps_restore@main
      - uses: TanklesXL/gleam_actions/.github/actions/install_gleam@main
        with:
          gleam_version: ${{ inputs.gleam_version }}
          erlang_version: ${{ matrix.erlang }}
      - run: ./test/create-database-postgres-gleam_cake_test.sh
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGPASSWORD: postgres
          PGUSER: postgres
      - uses: TanklesXL/gleam_actions/.github/actions/test@main
        with:
          target: "erlang"
